// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "discountapp/domain"
	inputs "discountapp/usecases/inputs"

	mock "github.com/stretchr/testify/mock"
)

// ICreateClient is an autogenerated mock type for the ICreateClient type
type ICreateClient struct {
	mock.Mock
}

// Perform provides a mock function with given fields: clientInput
func (_m *ICreateClient) Perform(clientInput *inputs.ClientInput) (*domain.Client, error) {
	ret := _m.Called(clientInput)

	var r0 *domain.Client
	if rf, ok := ret.Get(0).(func(*inputs.ClientInput) *domain.Client); ok {
		r0 = rf(clientInput)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*inputs.ClientInput) error); ok {
		r1 = rf(clientInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewICreateClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewICreateClient creates a new instance of ICreateClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICreateClient(t mockConstructorTestingTNewICreateClient) *ICreateClient {
	mock := &ICreateClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
