// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	"discountapp/usecases/outputs"

	mock "github.com/stretchr/testify/mock"
)

// IGetClients is an autogenerated mock type for the IGetClients type
type IGetClients struct {
	mock.Mock
}

// Perform provides a mock function with given fields:
func (_m *IGetClients) Perform() (*outputs.ClientsOutput, error) {
	ret := _m.Called()

	var r0 *outputs.ClientsOutput
	if rf, ok := ret.Get(0).(func() *outputs.ClientsOutput); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*outputs.ClientsOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIGetClients interface {
	mock.TestingT
	Cleanup(func())
}

// NewIGetClients creates a new instance of IGetClients. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIGetClients(t mockConstructorTestingTNewIGetClients) *IGetClients {
	mock := &IGetClients{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
