// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "discountapp/domain"

	mock "github.com/stretchr/testify/mock"
)

// IGetProducts is an autogenerated mock type for the IGetProducts type
type IGetProducts struct {
	mock.Mock
}

// Perform provides a mock function with given fields:
func (_m *IGetProducts) Perform() ([]*domain.Product, error) {
	ret := _m.Called()

	var r0 []*domain.Product
	if rf, ok := ret.Get(0).(func() []*domain.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIGetProducts interface {
	mock.TestingT
	Cleanup(func())
}

// NewIGetProducts creates a new instance of IGetProducts. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIGetProducts(t mockConstructorTestingTNewIGetProducts) *IGetProducts {
	mock := &IGetProducts{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
